template = "https://github.com/giellalt/template-lang-und"
rev_id = 316
template_sha = "4ab8b281df40078b127cd15db6e63507b51b4424"

[replacements]
__GLOTTOLOG_ID__ = "moha1258"
__REPO__ = "lang-moh"
__UND2C__ = "moh"
__UNDEFINED__ = "Mohawk"
__UND__ = "moh"
