template = "https://github.com/giellalt/template-lang-und"
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "moha1258"
__REPO__ = "lang-moh"
__UND2C__ = "moh"
__UNDEFINED__ = "Mohawk"
__UND__ = "moh"
