[package]
name = "moh"
human_name = "Mohawk"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.moh]
filename = "moh-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-moh"
platform = "windows"
uuid = "F6472F5F-18F7-465E-A966-7C7386AA0818"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.moh"
package = "speller-moh"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-moh-mso"
platform = "windows"
uuid = "E4FF2D06-DF1E-4AD1-B2CF-4EBAD9C32B0A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-moh"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
